SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE JOURNAL;
TRUNCATE TABLE LEARNING_DAY;
TRUNCATE TABLE ROLE;
TRUNCATE TABLE ROLE_GOAL;
TRUNCATE TABLE TEAM;
TRUNCATE TABLE TEAM_GOAL;
TRUNCATE TABLE TEAM_GOALS;
TRUNCATE TABLE TOPIC;
TRUNCATE TABLE TOPIC_CHILDREN_TOPICS;
TRUNCATE TABLE USER;
TRUNCATE TABLE WORKER;
TRUNCATE TABLE WORKER_GOAL;
TRUNCATE TABLE WORKER_GOAL;

SET REFERENTIAL_INTEGRITY TRUE